tests
pawsko/ToolRoom pull request #6
Opened 2022-12-09 08:34 UTC by pawsko

2022-12-14 08:00 UTC, brabram requested changes
I've checked category/rental - if similar code is in tool/user then comments are also valid for those tests :) ask in case of any doubts

2023-01-20 09:01 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryControllerTest.java
> +                .andDo(print())
ok

2023-01-20 09:04 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryControllerTest.java
> +        mockMvc.perform(get("/api/category/{id}", anyLong())
OK

2023-01-20 09:05 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryControllerTest.java
> +        mockMvc.perform(get("/api/category/{id}", "stringInsteadLong")
OK

2023-01-20 09:39 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryControllerTest.java
> +        CategoryDtoRequest categoryReq = new CategoryDtoRequest();
fixed

2023-01-20 09:40 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryControllerTest.java
> +                    .andExpect(jsonPath("$.categoryName", is(categoryReq.getCategoryName())));
I got acquainted

2023-01-20 09:45 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryDtoMapperTest.java
> +        CategoryDtoMapper categoryDtoMapper = new CategoryDtoMapper();
fixed

2023-01-20 09:47 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/category/CategoryServiceTest.java
> +
fixed

2023-01-20 09:48 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalControllerTest.java
> +            mockMvc.perform(post("/api/rental")
I got acquainted

2023-01-20 09:48 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalControllerTest.java
> +                    .andExpect(header().string(HttpHeaders.LOCATION, "http://localhost/api/rental/1"))
I got acquainted

2023-01-20 09:48 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalControllerTest.java
> +        mockMvc.perform(put("/api/rental/{id}", 100L)
I got acquainted

2023-01-20 09:53 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalControllerTest.java
> +        System.out.println(rentalRes1.getRented());
removed println

2023-01-20 09:55 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalControllerTest.java
> +        mapper.findAndRegisterModules();
moved

2023-01-20 10:00 UTC, pawsko commented on src/test/java/pl/pawsko/toolroom/rental/RentalDtoMapperTest.java
> +        Rental rental = new Rental(1L,
OK

2023-01-21 12:06 UTC, brabram approved these changes

2023-01-21 12:10 UTC, merged